### ISSUE TITLE
Feature request: TypeScript mode

### ISSUE THREAD

**Issue by dancrew32** [bchr02/CodeFlattener#1]
Hey great idea for a project, so thanks for sharing.

I think this project could be extra-valuable with typescript support (`.ts`). The goal would be to create flattened-code**.ts**

I'm thinking it's probably a little more than adding `.ts, .tsx` etc.. to the existing `[".js", ".mjs", ".json"]`. 

E.g. `npx codeflattener --output ./flattened-code.ts --include .ts --exclude .test.ts`

**Comment by bchr02** [comment]
Hey @dancrew32 ,

Thanks for reaching out. Great idea. I just pushed version 1.2 that includes this feature. Give it a try and let me know how it goes. thanks.
